In [1]:
import pandas as pd

tax_data  = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/tax_payers/train_set_label.csv" )

tax_data.head()

,Unnamed: 0,HHI,HHDL,Married,CollegGrads,AHHAge,Cars,Filed in 2017,Filed in 2016,Filed in 2015,PoliticalParty
0,61,183414,-12402,1,2,28,1,0,0,1,Democrat
1,501,129786,700251,2,5,63,3,0,0,0,Republican
2,658,268343,493411,2,4,44,1,1,0,1,Independent
3,703,290506,-433408,1,1,28,5,1,0,1,Republican
4,702,90108,907135,1,3,57,5,1,1,0,Democrat

In [2]:
#tax_data['PoliticalParty'].replace({'Democrat': 0, 'Republican': 1, 'Independant': 2}, inplace=True)
#tax_data['PoliticalParty'] = tax_data['PoliticalParty'].map({'Democrat': 0, 'Republican': 1, 'Independant': 2})
tax_data['PoliticalParty'].replace(to_replace = ['Democrat','Republican','Independent'], value =[0,1,2], inplace=True)
tax_data

,Unnamed: 0,HHI,HHDL,Married,CollegGrads,AHHAge,Cars,Filed in 2017,Filed in 2016,Filed in 2015,PoliticalParty
0,61,183414,-12402,1,2,28,1,0,0,1,0
1,501,129786,700251,2,5,63,3,0,0,0,1
2,658,268343,493411,2,4,44,1,1,0,1,2
3,703,290506,-433408,1,1,28,5,1,0,1,1
4,702,90108,907135,1,3,57,5,1,1,0,0
5,461,83914,693246,1,4,66,0,1,0,0,2
6,618,144029,-332420,0,3,90,2,0,1,0,0
7,5,157274,-472337,0,1,28,1,1,0,1,2
8,261,153930,494379,1,2,40,0,0,1,1,2
9,436,116951,560163,0,5,50,1,0,0,1,1
10,624,44860,-679922,1,2,32,3,0,1,0,0
11,563,184126,-55256,1,3,98,3,1,1,1,2
12,760,222779,338355,2,1,65,3,1,1,1,2
13,419,59406,-758380,1,4,24,0,0,0,0,1
14,856,229221,-600998,2,4,59,5,0,1,1,0
15,334,253084,-347310,2,4,69,1,1,0,1,2
16,936,171667,-719106,1,3,24,2,0,0,1,1
17,189,154817,-736638,0,3,46,5,0,0,1,0
18,29,244708,734172,0,4,33,1,0,1,1,2
19,773,276138,868661,0,2,37,3,1,1,1,2
20,278,43077,-959878,1,4,38,0,1,0,1,0
21,154,178409,5036,2,0,69,0,1,0,0,0
22,437,266989,-796477,1,0,45,4,1,1,0,0
23,991,190018,897005,0,3,45,3,1,0,1,2
24,134,16597,195542,1,1,24,2,0,0,0,0
25,220,281712,-751805,0,2,38,1,0,1,1,1
26,175,214242,-249444,1,3,50,3,0,1,0,2
27,836,239616,-20152,1,4,90,5,1,0,0,1
28,588,7994,-967282,1,4,73,5,0,1,1,1
29,153,105882,-623824,1,2,22,3,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
773,354,278836,239663,0,1,101,1,0,1,0,1
774,94,250992,571847,1,3,49,1,0,1,1,0
775,182,144741,90861,2,4,65,2,1,1,0,0
776,268,288902,-600704,0,3,23,1,0,0,1,0
777,85,244097,-535697,2,4,73,4,1,1,0,2
778,900,273740,-185691,1,2,64,5,1,1,1,1
779,155,19373,-115780,1,0,36,0,0,1,0,2
780,781,24157,878839,1,4,24,2,1,0,1,0
781,799,132975,497546,0,4,24,0,1,0,1,1
782,86,213667,-876390,0,4,73,2,1,0,1,1
783,985,182028,-68738,0,3,24,2,0,1,0,0
784,807,144275,734473,1,4,57,3,1,1,0,0
785,503,291713,619200,1,5,100,4,0,1,1,0
786,913,23175,-406831,2,4,35,1,0,1,1,0
787,782,253270,657514,1,5,65,5,0,1,1,1
788,889,181193,693718,2,0,75,2,0,0,0,1
789,784,296161,557947,0,5,94,1,0,1,1,0
790,434,267461,-290422,1,1,98,0,1,1,1,2
791,352,100603,14806,1,5,101,3,1,0,1,0
792,860,142073,111868,0,4,78,1,1,0,0,2
793,13,145298,-287587,0,3,62,1,1,0,1,1
794,390,33547,353240,2,2,21,1,0,1,1,1
795,255,258049,-505412,1,3,95,5,1,1,0,2
796,472,219152,441277,1,1,85,0,0,1,0,0
797,833,67176,728598,1,2,37,2,1,1,0,1
798,476,153304,971909,0,1,99,5,1,0,0,0
799,657,136652,-184616,1,2,31,3,1,0,0,0
800,596,51066,-900262,1,1,67,4,0,0,0,0
801,561,123721,-51448,2,0,23,4,0,1,1,1
802,635,189020,839546,2,4,56,1,0,0,0,1

In [3]:
Y = tax_data['PoliticalParty']

featureCols = ['Married', 'CollegGrads', 'Cars', 'Filed in 2017', 'Filed in 2016', 'Filed in 2015']
X = tax_data[featureCols]

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=365)

In [5]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)
y_pred=logreg.predict(x_test)

In [6]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.35094339622641507

In [7]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
model = XGBClassifier()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test, y_pred)*100)

36.60377358490566

In [8]:
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/tax_payers/test_set_label.csv')

In [9]:
test_data.head()

,Unnamed: 0,HHI,HHDL,Married,CollegGrads,AHHAge,Cars,Filed in 2017,Filed in 2016,Filed in 2015
0,17,253274,-633752,2,1,94,3,0,1,1
1,590,47107,322850,0,1,30,2,1,1,0
2,224,111874,300583,0,2,46,3,0,1,1
3,960,96670,107419,0,3,77,5,0,0,0
4,57,128669,341273,0,0,92,4,1,1,1

In [10]:
featureCols = ['Married', 'CollegGrads', 'Cars', 'Filed in 2017', 'Filed in 2016', 'Filed in 2015']
XTest = tax_data[featureCols]

In [11]:
YTest = logreg.predict(XTest)

In [12]:
YTest

array([2, 1, 2, 1, 1, 1, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 0, 2, 2, 1,
       1, 2, 0, 0, 0, 1, 2, 2, 1, 2, 2, 0, 1, 1, 0, 0, 1, 2, 0, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 0, 0, 1, 2, 2, 1, 2, 2, 0, 2, 0, 0, 0, 0, 1, 2,
       1, 0, 2, 0, 2, 1, 0, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 1, 1, 0, 2, 0,
       2, 1, 1, 1, 2, 0, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 2, 1, 0,
       0, 1, 2, 1, 1, 2, 2, 1, 0, 1, 2, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0,
       1, 0, 2, 1, 2, 1, 2, 1, 1, 1, 2, 0, 0, 2, 2, 1, 0, 0, 2, 2, 1, 1,
       0, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 0, 2, 0, 2, 2, 1, 2, 0, 2,
       2, 0, 0, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 2, 0, 0, 1, 0,
       2, 1, 1, 2, 2, 1, 1, 2, 1, 0, 2, 0, 2, 1, 2, 1, 0, 0, 0, 2, 2, 0,
       2, 2, 1, 2, 0, 1, 2, 2, 2, 1, 1, 2, 1, 0, 2, 1, 0, 2, 1, 0, 1, 1,
       1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 2, 2, 2, 2, 1, 1, 0, 0, 2, 2, 1, 1,
       0, 1, 0, 0, 1, 2, 2, 2, 2, 1, 0, 1, 2, 2, 1, 1, 2, 0, 1, 0, 1, 1,
       1, 0, 1, 2, 2, 1, 0, 0, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 1, 2, 2, 1,
       2, 0, 0, 1, 2, 2, 2, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 1, 1, 2, 2,
       0, 0, 2, 1, 2, 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2,
       0, 1, 1, 1, 2, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 2,
       1, 1, 1, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 2, 1, 2, 2, 2, 2, 1, 0, 2,
       2, 2, 0, 0, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 0, 2, 0, 0, 1, 1, 1, 0,
       2, 1, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 1, 2, 0, 1, 1, 1, 2, 1, 0, 2,
       2, 0, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 0, 0, 2, 1, 2, 2, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 0,
       2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 0, 2, 2, 0, 2, 2, 1, 0, 1, 2, 0,
       2, 0, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 2, 0, 0, 2, 2, 0, 1, 1, 2, 1,
       0, 0, 2, 2, 1, 0, 0, 1, 1, 2, 1, 0, 2, 1, 0, 1, 2, 1, 0, 1, 2, 2,
       1, 1, 2, 1, 2, 1, 1, 0, 2, 1, 2, 2, 2, 0, 1, 1, 2, 0, 0, 1, 2, 2,
       0, 0, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 0, 1,
       2, 2, 0, 0, 0, 2, 1, 1, 2, 1, 0, 0, 0, 2, 2, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0,
       2, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1, 1, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2,
       0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0,
       0, 1, 1, 0, 1, 2, 2, 1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 0, 0, 2, 1, 1, 0, 0, 2, 2, 0, 2, 0, 1, 0, 2, 2, 1, 0, 1, 1, 1,
       2, 1, 0, 0, 1, 0, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2,
       1, 1, 0, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 2, 2, 2, 1, 0, 2, 1,
       0, 2, 2, 1, 0, 1, 1, 1, 1, 2, 1], dtype=int64)

In [13]:
Final_Answers = ['prediction']
for i in YTest:
    if i == 0: Final_Answers.append('Democrat')
    elif i == 1: Final_Answers.append('Republican')
    elif i == 1: Final_Answers.append('Independent')
        
Final_Answers

['prediction',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Democrat',
 'Democrat',
 'Republican',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Democrat',
 'Republican',
 'Republican',
 'Republican',
 'Republican',
 'Republican']

In [14]:
rows = zip(Final_Answers)

In [16]:
import csv

with open(r'C:\\Users\shahe\Desktop\SSolwaSubmission.csv', "w", newline="") as f:
    writer = csv.writer(f)
    for row in rows:
        writer.writerow(row)