In [1]:
import pandas as pd

mo_data = pd.read_csv("Train_data (2).csv" )

mo_data.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Soil_Type_40,Cover_Type
0,2696,123,10,212,48,2245,237,231,123,2113,...,0,0,0,0,0,0,0,0,0,6
1,3269,110,19,134,40,3734,249,216,88,3960,...,0,0,0,0,0,0,1,0,0,1
2,3283,322,18,346,104,4369,170,217,185,1330,...,0,0,0,0,0,0,1,0,0,7
3,2847,89,31,270,175,1320,248,173,29,889,...,0,0,0,0,0,0,0,0,0,5
4,3248,93,12,507,118,570,239,221,110,945,...,0,0,0,0,0,0,0,0,0,7

In [2]:
mo_data.fillna('786')

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Soil_Type_40,Cover_Type
0,2696,123,10,212,48,2245,237,231,123,2113,...,0,0,0,0,0,0,0,0,0,6
1,3269,110,19,134,40,3734,249,216,88,3960,...,0,0,0,0,0,0,1,0,0,1
2,3283,322,18,346,104,4369,170,217,185,1330,...,0,0,0,0,0,0,1,0,0,7
3,2847,89,31,270,175,1320,248,173,29,889,...,0,0,0,0,0,0,0,0,0,5
4,3248,93,12,507,118,570,239,221,110,945,...,0,0,0,0,0,0,0,0,0,7
5,2855,162,5,85,4,2899,224,241,151,2568,...,0,0,0,0,0,0,0,0,0,2
6,2410,331,21,124,66,423,165,207,177,589,...,0,0,0,0,0,0,0,0,0,6
7,2151,337,30,67,31,784,137,180,172,491,...,0,0,0,0,0,0,0,0,0,3
8,3255,357,19,339,120,3829,185,199,148,3564,...,0,0,0,0,0,0,0,0,1,7
9,2291,32,7,0,0,487,218,224,142,831,...,0,0,0,0,0,0,0,0,0,4
10,2574,112,10,60,-8,1425,238,229,121,1227,...,0,0,0,0,0,0,0,0,0,3
11,2278,199,19,196,97,1167,209,252,171,1139,...,0,0,0,0,0,0,0,0,0,4
12,2773,38,13,291,60,2637,219,210,123,234,...,0,0,0,0,0,0,0,0,0,5
13,2866,341,11,295,35,2382,197,224,165,2518,...,0,0,0,0,0,0,0,0,0,2
14,2724,146,16,30,0,2356,240,236,121,6534,...,0,0,0,0,0,0,0,0,0,2
15,2323,21,8,86,11,260,215,222,144,1245,...,0,0,0,0,0,0,0,0,0,6
16,3297,338,15,0,0,3993,184,216,169,1061,...,0,0,0,0,0,0,1,0,0,7
17,2094,128,16,30,6,904,244,228,105,774,...,0,0,0,0,0,0,0,0,0,4
18,3067,142,24,603,-9,891,246,226,95,2440,...,0,0,0,0,0,0,0,0,0,1
19,3031,274,25,311,36,1676,144,236,226,3342,...,0,0,0,0,0,0,0,0,0,1
20,2446,152,13,57,6,1825,235,240,131,125,...,0,0,0,0,0,0,0,0,0,3
21,2488,106,12,30,-2,1687,241,224,110,835,...,0,0,0,0,0,0,0,0,0,3
22,3283,358,23,718,122,1393,176,188,142,1555,...,0,0,0,0,0,0,0,1,0,7
23,3004,127,9,134,19,4227,236,234,129,3975,...,0,0,0,0,0,0,0,0,0,2
24,3394,68,27,117,55,1915,235,175,53,1000,...,0,0,0,0,0,0,0,1,0,7
25,3373,332,32,274,48,3685,131,181,179,3772,...,0,0,0,0,0,0,0,1,0,7
26,2577,53,8,422,49,648,225,221,130,1227,...,0,0,0,0,0,0,0,0,0,6
27,3220,158,37,137,61,1551,229,215,80,571,...,0,0,0,0,0,0,0,1,0,7
28,2893,116,10,224,39,2280,238,229,120,662,...,0,0,0,0,0,0,0,0,0,5
29,3321,322,28,162,71,1861,137,199,195,2550,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249970,3296,292,7,150,12,4931,199,239,178,3128,...,0,0,0,0,0,0,1,0,0,7
249971,3302,3,13,512,78,2882,201,214,148,3379,...,1,0,0,0,0,0,0,0,0,7
249972,2323,215,14,380,29,1270,215,246,161,882,...,0,0,0,0,0,0,0,0,0,4
249973,3178,16,6,272,39,2748,215,227,149,3648,...,0,0,0,0,0,0,0,0,0,1
249974,3261,311,5,592,84,751,207,236,168,726,...,0,0,0,0,0,0,0,0,0,1
249975,2777,309,7,0,0,2190,198,235,176,814,...,0,0,0,0,0,0,0,0,0,5
249976,3039,142,27,240,66,2751,247,223,87,1504,...,0,1,0,0,0,0,0,0,0,2
249977,2322,23,34,244,80,599,178,145,81,456,...,0,0,0,0,0,0,0,0,0,6
249978,1975,159,20,54,9,177,236,239,123,455,...,0,0,0,0,0,0,0,0,0,3
249979,2730,197,19,240,-5,641,212,252,168,636,...,0,0,1,0,0,0,0,0,0,2
249980,3304,327,12,620,49,3493,190,226,175,3558,...,0,0,0,0,0,0,0,0,1,7
249981,3311,279,25,532,205,480,146,234,224,912,...,0,0,0,0,0,0,0,0,0,1
249982,2946,4,16,85,13,698,197,207,145,1871,...,0,0,0,0,0,0,0,0,0,1
249983,2497,317,27,258,111,780,139,205,201,1273,...,0,0,0,0,0,0,0,0,0,2
249984,3137,43,3,0,0,2060,220,232,148,2577,...,0,0,0,0,0,0,0,0,0,7
249985,2802,47,14,236,144,245,224,208,115,1384,...,0,0,0,0,0,0,0,0,0,5
249986,2187,101,15,9,1,1474,243,217,98,537,...,0,0,0,0,0,0,0,0,0,4
249987,3148,56,19,447,123,2158,229,194,90,1805,...,0,1,0,0,0,0,0,0,0,1
249988,2281,176,11,173,42,1655,226,245,150,812,...,0,0,0,0,0,0,0,0,0,6
249989,2647,345,20,195,36,2063,175,202,162,2517,...,0,0,0,0,0,0,0,0,0,6
249990,3373,93,12,574,216,1409,239,220,109,989,...,0,0,0,0,0,0,0,1,0,7
249991,2131,20,18,162,40,300,204,198,126,404,...,0,0,0,0,0,0,0,0,0,6
249992,2843,198,9,857,67,2283,217,248,164,1620,...,0,0,0,0,0,0,0,0,0,5
249993,2714,127,11,0,0,1444,238,232,122,1378,...,0,0,0,0,0,0,0,0,0,5
249994,2611,111,14,345,66,1561,243,223,106,1789,...,0,0,0,0,0,0,0,0,0,3
249995,2112,339,39,49,17,467,107,151,162,435,...,0,0,0,0,0,0,0,0,0,3
249996,2872,90,31,251,147,2027,248,172,27,508,...,0,0,0,0,0,0,0,0,0,5
249997,2336,57,5,0,0,1429,224,228,139,387,...,0,0,0,0,0,0,0,0,0,4
249998,2563,181,10,0,0,1349,223,246,156,1007,...,0,0,0,0,0,0,0,0,0,5
249999,3720,354,17,1112,311,5105,189,208,155,3256,...,0,0,0,0,0,0,0,0,1,7

In [3]:
X = mo_data.drop(['Cover_Type'], axis=1)
Y = mo_data['Cover_Type']

print(X.shape)
print(Y.shape)

xData = X.values
yData = Y.values

(250000, 54)
(250000,)

In [17]:
from sklearn.model_selection import train_test_split 

xTrain, xTest, yTrain, yTest = train_test_split( 
        xData, yData, test_size = 0.01, random_state = 0)

In [9]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
model = XGBClassifier()
model.fit(xTrain, yTrain)
y_pred=model.predict(xTest)
print(accuracy_score(yTest, y_pred)*100)

92.35515151515152

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
clf = RandomForestClassifier(max_depth=50)
clf.fit(xTrain, yTrain)
y_pred = clf.predict(xTest)
print(accuracy_score(yTest, y_pred)*100)

In [14]:
test_data = pd.read_csv('Test_data (2).csv')
test_data.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_31,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Soil_Type_40
0,2157,345,11,0,0,1103,198,222,161,823,...,0,0,0,0,0,0,0,0,0,0
1,2740,40,23,94,-13,150,214,179,88,1307,...,0,0,0,0,0,0,0,0,0,0
2,2404,46,11,558,110,625,223,215,124,1051,...,0,0,0,0,0,0,0,0,0,0
3,3002,201,23,256,35,4582,204,253,173,1708,...,0,0,0,0,0,0,0,0,0,0
4,2360,306,6,136,57,1054,202,236,173,862,...,0,0,0,0,0,0,0,0,0,0

In [15]:
print(len(test_data))
vals = clf.predict(test_data.values)

50000

In [16]:
res = pd.DataFrame(vals)
res.columns = ["prediction"]
res.to_csv("Forrest_Cover_preds.csv", index = False)